Add navbar
inventables/ecomm-theme-dawn pull request #20
Opened 2023-04-18 20:49 UTC by nina-inventables

### PR Summary: 
update header navbar

### Why are these changes introduced?

Fixes #0.

### What approach did you take?

### Other considerations

### Decision log

| # | Decision | Alternatives | Rationale | Downsides |
|---|---|---|---|---|
| 1 |   |   |   |   |

### Visual impact on existing themes

### Testing steps/scenarios

- [ ] Step 1

### Demo links

- [Store](url)
- [Editor](url)

### Checklist
- [ ] Added PR summary for [release notes](https://themes.shopify.com/themes/dawn/styles/default#ReleaseNotes)
- [ ] Requested review from UX (Only for changes that are affecting the experience or perceivable visual details)
- [ ] Created a ticket for the [help.shopify.com](https://help.shopify.com) documentation team about updates to theme settings. (Internal-only task)
- [ ] Followed [theme code principles](https://github.com/Shopify/dawn/blob/main/.github/CONTRIBUTING.md#theme-code-principles)
- [ ] Linted with [Theme Check](https://github.com/Shopify/theme-check)
- [ ] Tested on [mobile](https://shopify.dev/themes/store/requirements#mobile-browser-requirements)
- [ ] Tested on [multiple browsers](https://shopify.dev/themes/store/requirements#desktop-browser-requirements)
- [ ] Tested for [accessibility](https://shopify.dev/themes/best-practices/accessibility)

2023-04-20 21:44 UTC, natedemery requested changes

2023-04-20 21:44 UTC, natedemery commented on assets/base.css
> +/* .header__icon--cart {
Remove commented code

2023-04-20 21:44 UTC, natedemery commented on assets/base.css
> +/* .header__icon:hover .icon,
Remove commented code.

2023-04-24 20:32 UTC, gensym approved these changes

2023-04-25 14:59 UTC, merged