X-Carve PRO 4x4 and 4x2
inventables/ecomm-theme-dawn pull request #52
Opened 2023-05-25 23:00 UTC by arthurstomp

### PR Summary: 

This PR add a layout, templates and sections for the implementation of X-Carve PRO product pages, 4x4 and 4x2, as especified on [Figma](https://www.figma.com/file/Dzfu2ajVNiRoYmVS5IGGGd/X-Carve-Pro-Webpages---Delivery?type=design&node-id=1-672&t=57PENUmMhaz6IlMe-0)

Because multiple sections of that template depends on which size of XCP is the page for, i've made the template of 4x2 a copy 4x4. That way each template can be attached to the correspondent product.

![1685055132](https://github.com/inventables/ecomm-theme-dawn/assets/1282750/5ce28879-6feb-4451-b171-553251105368)

### Why are these changes introduced?

Fixes #0.

### What approach did you take?

### Other considerations

### Decision log

| # | Decision | Alternatives | Rationale | Downsides |
|---|---|---|---|---|
| 1 |   |   |   |   |

### Visual impact on existing themes

### Testing steps/scenarios

- [ ] Step 1

### Demo links

- [Store](https://inventablesusa.myshopify.com/admin/themes)
- [Editor](https://inventablesusa.myshopify.com/admin/themes/130564456505/editor?previewPath=%2Fproducts%2Fx-carve-pro)

### Checklist
- [ ] Added PR summary for [release notes](https://themes.shopify.com/themes/dawn/styles/default#ReleaseNotes)
- [ ] Requested review from UX (Only for changes that are affecting the experience or perceivable visual details)
- [ ] Created a ticket for the [help.shopify.com](https://help.shopify.com) documentation team about updates to theme settings. (Internal-only task)
- [ ] Followed [theme code principles](https://github.com/Shopify/dawn/blob/main/.github/CONTRIBUTING.md#theme-code-principles)
- [ ] Linted with [Theme Check](https://github.com/Shopify/theme-check)
- [ ] Tested on [mobile](https://shopify.dev/themes/store/requirements#mobile-browser-requirements)
- [ ] Tested on [multiple browsers](https://shopify.dev/themes/store/requirements#desktop-browser-requirements)
- [ ] Tested for [accessibility](https://shopify.dev/themes/best-practices/accessibility)

2023-05-26 15:25 UTC, natedemery requested changes

2023-05-26 15:25 UTC, natedemery commented on assets/xcp-navbar.css
> +        /* padding:8px 16px; */
@arthurstomp Remove all commented code.

2023-05-31 15:14 UTC, thomasjlee commented
Hi @arthurstomp we got the Case Study videos from our Marketing Team.

Please refer to the comment in [this fbolt Issue](https://github.com/inventables/fbolt/issues/6150#issuecomment-1569150948)

For the cover image (image before video is played), we will ask Marketing to provide it. Leave it as the default for now. Let us know if you have any questions. Thanks!

2023-06-01 21:41 UTC, natedemery approved these changes

2023-06-02 19:19 UTC, natedemery approved these changes

2023-06-02 19:24 UTC, arthurstomp commented
Moved into https://github.com/inventables/ecomm-theme-dawn/pull/56

2023-06-02 19:24 UTC, closed without merging