X-Carve product page
inventables/ecomm-theme-dawn pull request #60
Opened 2023-06-07 12:47 UTC by arthurstomp

### PR Summary: 

This PR implements the shopify template for X-Carve product as it is implemented on inventables.com

[Preview](https://clfmzevs1qhy49by-60429828153.shopifypreview.com/products/x-carve-1) | [Editor](https://inventablesusa.myshopify.com/admin/themes/130585100345/editor?previewPath=%2Fproducts%2Fx-carve-1)

![screencapture-localhost-9292-products-x-carve-1-2023-06-07-09_46_24](https://github.com/inventables/ecomm-theme-dawn/assets/1282750/951b6bb2-9052-427e-92d9-e577e9ac4865)

### Why are these changes introduced?

Fixes #0.

### What approach did you take?

### Other considerations

### Decision log

| # | Decision | Alternatives | Rationale | Downsides |
|---|---|---|---|---|
| 1 |   |   |   |   |

### Visual impact on existing themes

### Testing steps/scenarios

- [ ] Step 1

### Demo links

- [Store](url)
- [Editor](url)

### Checklist
- [ ] Added PR summary for [release notes](https://themes.shopify.com/themes/dawn/styles/default#ReleaseNotes)
- [ ] Requested review from UX (Only for changes that are affecting the experience or perceivable visual details)
- [ ] Created a ticket for the [help.shopify.com](https://help.shopify.com) documentation team about updates to theme settings. (Internal-only task)
- [ ] Followed [theme code principles](https://github.com/Shopify/dawn/blob/main/.github/CONTRIBUTING.md#theme-code-principles)
- [ ] Linted with [Theme Check](https://github.com/Shopify/theme-check)
- [ ] Tested on [mobile](https://shopify.dev/themes/store/requirements#mobile-browser-requirements)
- [ ] Tested on [multiple browsers](https://shopify.dev/themes/store/requirements#desktop-browser-requirements)
- [ ] Tested for [accessibility](https://shopify.dev/themes/best-practices/accessibility)

2023-06-12 14:52 UTC, nina-inventables approved these changes
LG

2023-06-22 15:21 UTC, nina-inventables requested changes
Can you fix the merge conflicts? @arthurstomp

2023-06-23 00:12 UTC, arthurstomp commented
@nina-inventables fixed

2023-06-26 14:53 UTC, nina-inventables approved these changes

2023-06-26 15:35 UTC, merged