Fxsd 257/base
inventables/ecomm-theme-dawn pull request #92
Opened 2023-09-07 18:42 UTC by duduneto

### PR Summary: 

This PR will include a new homepage template and 3 additional template pages (Furniture Maker, Sign Maker, General Maker). Also a new layout for the industries theme is created.

### Why are these changes introduced?

Homepage, Furniture Maker, Sign Maker, General Maker template pages.

### Visual impact on existing themes
Will add a `Industries` layout to the current theme.

### Demo links
`Development Env`

- [Store](https://foxbox-inventables-dev.myshopify.com/)
- [Editor](https://admin.shopify.com/store/foxbox-inventables-dev/themes/159211127078/editor)

2023-09-11 19:14 UTC, thomasjlee requested changes
Hi @duduneto, this is looking good!

I added a comment about the `CFH` variable in `industries.liquid`.

Also I noticed the main navigation is no longer sticky. It should behave like this:

https://github.com/inventables/ecomm-theme-dawn/assets/26750330/b27e6521-4437-4813-9aae-a483a811c47c

2023-09-11 19:14 UTC, thomasjlee commented on layout/industries.liquid
> +
Please remove these lines. We no longer need `CFH`.

2023-09-12 17:41 UTC, duduneto commented on layout/industries.liquid
> +
Solved!

2023-09-12 18:51 UTC, natedemery commented
@duduneto can you rebase this PR? There are some merge conflicts.

2023-09-12 20:20 UTC, thomasjlee approved these changes

2023-09-13 20:11 UTC, natedemery approved these changes

2023-09-13 20:12 UTC, merged